image:
  name: hashicorp/terraform:0.11.11
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  DOCKER_HOST: tcp://127.0.0.1:2375/    

before_script:
  - rm -rf .terraform
  - terraform --version
  - sed -i '3s/my-access-key/'$AWS_ACCESS_KEY'/' aws-demo.tf
  - sed -i '4s/my-secret-key/'$AWS_SECRET_KEY'/' aws-demo.tf
  - echo  $aws_pem |base64 -d >./minaterraform.pem
  - cat ./aws-demo.tf
  - echo $availability_zone >./aws-demo.tfvars
  - echo "key_name="'"'$key_name'"' >>./aws-demo.tfvars
  - echo $ec2_count >>./aws-demo.tfvars
  - echo $private_key_path >>./aws-demo.tfvars
  - cat ./aws-demo.tfvars
  - terraform init -input=false

# stages:
#   - validate
#   - plan
#   - apply
#   - destroy

# validate:
#   stage: validate
#   script:
#     - terraform validate -var-file=aws-demo.tfvars

# plan:
#   stage: plan
#   script:
#     - terraform plan -var-file=aws-demo.tfvars -out "planfile"
#   dependencies:
#     - validate
#   artifacts:
#     paths:
#       - planfile

# apply:
#   stage: apply
#   script:
#     - terraform apply -var-file=aws-demo.tfvars -input=false "planfile"
#   dependencies:
#     - plan
# destroy:
#   stage: destroy
#   script:
#     - terraform destroy -force
#   when: manual    
