image:
  name: hashicorp/terraform:0.11.11
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  DOCKER_HOST: tcp://127.0.0.1:2375/    

before_script:
  - rm -rf .terraform
  - terraform --version
  - pwd
  - sed -i '3s/123456/'$AWS_ACCESS_KEY'/' provider.tf
  - sed -i '4s/my-secret-key/'$AWS_SECRET_KEY'/' provider.tf
  - cat ./minaterraform.pem |base64
  - echo  $aws_pem |base64 -d >2.pem
  - diff ./2.pem ./minaterraform.pem
  - cat ./provider.tf
  - terraform init

stages:
  - validate
#   - plan
#   - apply

validate:
  stage: validate
  script:
    - terraform validate

# plan:
#   stage: plan
#   script:
#     - terraform plan -out "planfile"
#   dependencies:
#     - validate
#   artifacts:
#     paths:
#       - planfile

# apply:
#   stage: apply
#   script:
#     - terraform apply -input=false "planfile"
#   dependencies:
#     - plan
